auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            Higher
url:              http://feidegenggao.github.com
feed:             /atom.xml
author:
    name:         Higher
    twitter:      twitter.com/beiyuu
description:      "Higher\'s Blog"
author_info:      <a href="http://feidegenggao.github.com/about">Higher</a>

copyright:
    - Design by <a href="http://beiyuu.com/about" title="BeiYuu" target="_blank">BeiYuu</a> &copy; 2013
